### ISSUE TITLE
Add required class to introspected validation fields

### ISSUE THREAD

**Issue by hew** [Foodee/ember-foxy-forms#301]
https://github.com/Foodee/ember-foxy-forms/pull/285 introduced the ability for Foxy Form to self-identify required fields eliminating the need to have `@required={{true}}` in the template code. 

However, `@required` is still needed for Foxy Forms to set the 'required' class, which is needed for CSS purposes, ie: 

```css
.form-for .field-for.required > label::after {
  content: "*";
  color: #e93c3c;
}
```
